// src/components/MembershipCard.tsx
import type { ReactNode } from 'react'

export const CARD_WIDTH = 1280
export const CARD_HEIGHT = 760

export type CardSide = 'front' | 'back'

export type MembershipCardMember = {
  id: string
  member_no: string | null
  full_name: string
  father_name: string
  cnic: string
  mobile: string
  district: string
  taluka: string | null
  profession: string | null
  caste_branch: string | null
  photo_url: string
  status: 'pending' | 'approved' | 'rejected'
  approved_at: string | null

  address: string | null
  date_of_birth: string | null
  gender: string | null
  education: string | null
  blood_group: string | null
  emergency_contact_name: string | null
  emergency_contact_relation: string | null
  emergency_contact_mobile: string | null
  declaration_accepted: boolean
}

type MembershipCardProps = {
  side: CardSide
  member: MembershipCardMember
  photoUrl: string | null
  logoUrl: string | null
  flagUrl: string | null
  qrUrl: string | null
  verifyUrl: string
}

export function MembershipCard({
  side,
  member,
  photoUrl,
  logoUrl,
  flagUrl,
  qrUrl,
  verifyUrl,
}: MembershipCardProps) {
  return (
    <article
      className="relative flex shrink-0 flex-col overflow-hidden rounded-[2rem] border border-emerald-900/20 bg-white text-slate-950 shadow-2xl"
      style={{
        width: `${CARD_WIDTH}px`,
        minWidth: `${CARD_WIDTH}px`,
        height: `${CARD_HEIGHT}px`,
      }}
    >
      {side === 'front' ? (
        <CardFront
          member={member}
          photoUrl={photoUrl}
          logoUrl={logoUrl}
          flagUrl={flagUrl}
          qrUrl={qrUrl}
          verifyUrl={verifyUrl}
        />
      ) : (
        <CardBack
          member={member}
          logoUrl={logoUrl}
          flagUrl={flagUrl}
          qrUrl={qrUrl}
          verifyUrl={verifyUrl}
        />
      )}
    </article>
  )
}

function CardFront({
  member,
  photoUrl,
  logoUrl,
  flagUrl,
  qrUrl,
  verifyUrl,
}: Omit<MembershipCardProps, 'side'>) {
  const professionOrCaste =
    member.profession || member.caste_branch || 'Not provided'

  return (
    <>
      <CardHeader
        logoUrl={logoUrl}
        label="Digital Member ID"
        title="JATT ALLIANCE SINDH"
        subtitle="Official verified membership card"
        badge="Verified"
      />

      <div className="relative flex-1 overflow-hidden bg-white">
        <SoftBackground logoUrl={logoUrl} flagUrl={flagUrl} />

        <div className="relative grid h-full grid-cols-[250px_1fr_220px] gap-8 p-8">
          <div className="space-y-4">
            {photoUrl ? (
              <img
                src={photoUrl}
                alt={member.full_name}
                className="h-[240px] w-[240px] rounded-[2rem] border-4 border-white object-cover shadow-lg ring-2 ring-yellow-300/80"
              />
            ) : (
              <div className="flex h-[240px] w-[240px] items-center justify-center rounded-[2rem] bg-slate-100 text-sm text-slate-500 shadow-sm ring-2 ring-yellow-300/60">
                No photo
              </div>
            )}

            <div className="rounded-[1.4rem] border border-yellow-300 bg-emerald-950 px-4 py-4 text-center shadow-sm">
              <p className="text-[13px] font-black uppercase tracking-wide text-yellow-300">
                Member No
              </p>
              <p className="mt-1 text-[20px] font-black text-white">
                {member.member_no}
              </p>
            </div>
          </div>

          <div className="space-y-6">
            <div>
              <p className="text-[18px] font-bold uppercase tracking-wide text-slate-500">
                Member Name
              </p>
              <h3 className="mt-2 text-[44px] font-black leading-tight text-slate-950">
                {member.full_name}
              </h3>
            </div>

            <div className="grid grid-cols-2 gap-x-12 gap-y-6">
              <Info label="Father Name" value={member.father_name} />
              <Info label="District" value={member.district} />
              <Info label="Taluka" value={member.taluka || 'Not provided'} />
              <Info label="Profession / Caste" value={professionOrCaste} />
              <Info
                label="Approved Date"
                value={formatDate(member.approved_at)}
              />
              <Info label="Status" value="Approved" />
            </div>
          </div>

          <QrPanel qrUrl={qrUrl} />
        </div>
      </div>

      <div className="border-t border-slate-200 bg-slate-50 px-8 py-5">
        <p className="text-[14px] leading-6 text-slate-500">
          This card is digitally generated by Jatt Alliance Sindh. QR
          verification confirms current membership status.
          {verifyUrl ? (
            <span className="ml-1 break-all">
              Verification URL: {verifyUrl}
            </span>
          ) : null}
        </p>
      </div>
    </>
  )
}

function CardBack({
  member,
  logoUrl,
  flagUrl,
  qrUrl,
  verifyUrl,
}: Omit<MembershipCardProps, 'side' | 'photoUrl'>) {
  return (
    <>
      <CardHeader
        logoUrl={logoUrl}
        label="Jatt Alliance Sindh"
        title="CARDHOLDER DETAILS"
        subtitle="Verification, terms and issuing authority"
        badge="Back Side"
      />

      <div className="relative flex-1 overflow-hidden bg-white">
        <SoftBackground logoUrl={logoUrl} flagUrl={flagUrl} />

        <div className="relative grid h-full grid-cols-[1fr_255px] gap-6 p-7">
          <div className="grid grid-cols-2 gap-4">
            <BackPanel title="Residential Address">
              {member.address ? (
                <p className="font-bold text-slate-950">{member.address}</p>
              ) : (
                <p className="text-slate-600">
                  Full street address not collected yet.
                </p>
              )}
              <p className="mt-1 font-bold text-slate-950">
                {member.taluka || 'Taluka not provided'}, {member.district}
              </p>
            </BackPanel>

            <BackPanel title="Emergency Contact">
              {member.emergency_contact_name ||
              member.emergency_contact_mobile ? (
                <>
                  <p className="font-bold text-slate-950">
                    {member.emergency_contact_name || 'Name not provided'}
                  </p>
                  <p>
                    {member.emergency_contact_relation || 'Relation not provided'}
                  </p>
                  <p className="font-bold text-slate-950">
                    {member.emergency_contact_mobile || 'Mobile not provided'}
                  </p>
                </>
              ) : (
                <>
                  <p className="font-bold text-slate-950">Not collected yet.</p>
                  <p className="mt-1 text-slate-600">
                    Emergency contact can be added later.
                  </p>
                </>
              )}
            </BackPanel>

            <BackPanel title="Member Information">
              <div className="grid grid-cols-2 gap-x-4 gap-y-2">
                <MiniInfo
                  label="DOB"
                  value={formatDate(member.date_of_birth)}
                />
                <MiniInfo
                  label="Gender"
                  value={member.gender || 'Not provided'}
                />
                <MiniInfo
                  label="Blood"
                  value={member.blood_group || 'Not provided'}
                />
                <MiniInfo
                  label="Education"
                  value={member.education || 'Not provided'}
                />
              </div>
            </BackPanel>

            <BackPanel title="Verification Instructions">
              <p>Scan the QR code or open the verification URL.</p>
              <p className="mt-1">
                Match the verified name, member number, district and status
                before accepting this card as valid.
              </p>
            </BackPanel>

            <BackPanel title="Terms and Conditions">
              <ul className="list-disc space-y-1 pl-5">
                <li>This card remains property of Jatt Alliance Sindh.</li>
                <li>Misuse, alteration or transfer is not permitted.</li>
                <li>Validity depends on live verification status.</li>
              </ul>
            </BackPanel>

            <BackPanel title="Issuing Authority">
              <div className="mt-5 h-px w-56 bg-slate-400" />
              <p className="mt-2 font-black text-slate-950">
                Authorized Signature
              </p>
              <p className="mt-1 text-slate-600">Digital membership office</p>
            </BackPanel>
          </div>

          <div className="flex flex-col justify-between rounded-[2rem] border border-slate-200 bg-white/95 p-4 shadow-sm">
            <div className="rounded-2xl border border-yellow-300 bg-emerald-950 px-3 py-3 text-center shadow-sm">
              <p className="text-[12px] font-black uppercase tracking-wide text-yellow-300">
                Issue No / Version
              </p>
              <p className="mt-1 text-[18px] font-black text-white">
                {member.member_no ? `${member.member_no} / v1` : 'Pending / v1'}
              </p>
            </div>

            <div className="text-center">
              {qrUrl ? (
                <img
                  src={qrUrl}
                  alt="Verification QR"
                  className="mx-auto h-[175px] w-[175px] rounded-xl bg-white p-2"
                />
              ) : (
                <div className="mx-auto h-[175px] w-[175px] rounded-xl bg-slate-100" />
              )}

              <p className="mt-3 text-center text-[13px] font-semibold uppercase tracking-wide text-slate-500">
                Scan to verify
              </p>
            </div>

            <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-[12px] font-black uppercase tracking-wide text-slate-500">
                Verification URL
              </p>
              <p className="mt-1 break-all text-[12px] font-bold leading-5 text-slate-950">
                {verifyUrl}
              </p>
            </div>

            <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3">
              <p className="text-[12px] font-black uppercase tracking-wide text-slate-500">
                Organization Contact
              </p>
              <p className="mt-1 text-[13px] font-bold leading-5 text-slate-950">
                Jatt Alliance Sindh
              </p>
              <p className="text-[12px] font-semibold text-slate-600">
                Sindh, Pakistan
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="border-t border-slate-200 bg-slate-50 px-8 py-4">
        <p className="text-[13px] leading-5 text-slate-500">
          This card is valid only when the QR verification page confirms the
          membership as approved and active.
        </p>
      </div>
    </>
  )
}

function CardHeader({
  logoUrl,
  label,
  title,
  subtitle,
  badge,
}: {
  logoUrl: string | null
  label: string
  title: string
  subtitle: string
  badge: string
}) {
  return (
    <div className="relative h-[200px] overflow-hidden bg-gradient-to-r from-emerald-950 via-emerald-900 to-teal-800 px-8 py-7 text-white">
      <div className="absolute right-0 top-0 h-48 w-48 rounded-bl-full bg-yellow-300/12" />
      <div className="absolute bottom-0 left-0 h-32 w-32 rounded-tr-full bg-white/8" />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(250,204,21,0.16),transparent_34%)]" />

      <div className="relative flex items-start justify-between gap-6">
        <div className="flex items-start gap-5">
          <LogoMark logoUrl={logoUrl} />

          <div className="max-w-[760px]">
            <p className="text-[14px] font-black uppercase tracking-[0.38em] text-yellow-300">
              {label}
            </p>

            <h2 className="mt-3 whitespace-nowrap text-[58px] font-black uppercase leading-[0.94] tracking-tight text-white">
              {title}
            </h2>

            <p className="mt-3 text-[16px] font-medium text-emerald-50">
              {subtitle}
            </p>
          </div>
        </div>

        <div className="min-w-[170px] whitespace-nowrap rounded-[1.1rem] border border-yellow-300/70 bg-yellow-300 px-7 py-4 text-center text-[18px] font-black uppercase tracking-wide text-emerald-950 shadow-lg">
          {badge}
        </div>
      </div>
    </div>
  )
}

function LogoMark({ logoUrl }: { logoUrl: string | null }) {
  return logoUrl ? (
    <img
      src={logoUrl}
      alt="Jatt Alliance Sindh logo"
      className="mt-1 h-24 w-24 rounded-full border-2 border-yellow-400 bg-white object-cover shadow-xl"
    />
  ) : (
    <div className="mt-1 flex h-24 w-24 items-center justify-center rounded-full border-2 border-yellow-400 bg-emerald-950 text-xl font-black text-yellow-300 shadow-xl">
      JAS
    </div>
  )
}

function SoftBackground({
  logoUrl,
  flagUrl,
}: {
  logoUrl: string | null
  flagUrl: string | null
}) {
  return (
    <>
      {flagUrl ? (
        <>
          <img
            src={flagUrl}
            alt=""
            className="pointer-events-none absolute inset-0 h-full w-full object-cover opacity-[0.10] mix-blend-multiply"
          />
          <div className="pointer-events-none absolute inset-0 bg-white/[0.78]" />
          <div className="pointer-events-none absolute inset-0 bg-gradient-to-r from-white/[0.92] via-white/[0.82] to-white/[0.72]" />
        </>
      ) : null}

      {logoUrl ? (
        <img
          src={logoUrl}
          alt=""
          className="pointer-events-none absolute left-1/2 top-1/2 h-[460px] w-[460px] -translate-x-1/2 -translate-y-1/2 rounded-full object-cover opacity-[0.045]"
        />
      ) : null}
    </>
  )
}

function Info({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[14px] font-bold uppercase tracking-wide text-slate-500">
        {label}
      </p>
      <p className="mt-2 text-[20px] font-bold leading-tight text-slate-950">
        {value}
      </p>
    </div>
  )
}

function MiniInfo({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[11px] font-black uppercase tracking-wide text-emerald-800">
        {label}
      </p>
      <p className="mt-1 text-[13px] font-bold leading-4 text-slate-950">
        {value}
      </p>
    </div>
  )
}

function BackPanel({
  title,
  children,
}: {
  title: string
  children: ReactNode
}) {
  return (
    <section className="rounded-[1.25rem] border border-slate-200 bg-white/90 p-4 shadow-sm">
      <h3 className="text-[13px] font-black uppercase tracking-[0.22em] text-emerald-800">
        {title}
      </h3>
      <div className="mt-2 text-[15px] font-semibold leading-5 text-slate-700">
        {children}
      </div>
    </section>
  )
}

function QrPanel({ qrUrl }: { qrUrl: string | null }) {
  return (
    <div className="flex items-center justify-center">
      <div className="flex h-[340px] w-[200px] flex-col items-center justify-center rounded-[2rem] border border-slate-200 bg-white/95 p-4 shadow-sm">
        {qrUrl ? (
          <img
            src={qrUrl}
            alt="Verification QR"
            className="h-[150px] w-[150px] rounded-xl bg-white p-2"
          />
        ) : (
          <div className="h-[150px] w-[150px] rounded-xl bg-slate-100" />
        )}

        <p className="mt-5 text-center text-[14px] font-semibold uppercase tracking-wide text-slate-500">
          Scan to verify
        </p>
      </div>
    </div>
  )
}

function formatDate(value: string | null) {
  return value ? new Date(value).toLocaleDateString() : 'N/A'
}
