/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardRouteImport } from './routes/card'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyMemberNoRouteImport } from './routes/verify/$memberNo'
import { Route as ProgramsWelfareRouteImport } from './routes/programs/welfare'
import { Route as ProgramsHealthRouteImport } from './routes/programs/health'
import { Route as ProgramsEmploymentRouteImport } from './routes/programs/employment'
import { Route as ProgramsEducationRouteImport } from './routes/programs/education'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as ProgramsWelfareMyApplicationsRouteImport } from './routes/programs/welfare/my-applications'
import { Route as ProgramsWelfareApplyRouteImport } from './routes/programs/welfare/apply'
import { Route as ProgramsWelfareIdRouteImport } from './routes/programs/welfare/$id'
import { Route as ProgramsHealthMyApplicationsRouteImport } from './routes/programs/health/my-applications'
import { Route as ProgramsHealthApplyRouteImport } from './routes/programs/health/apply'
import { Route as ProgramsHealthIdRouteImport } from './routes/programs/health/$id'
import { Route as ProgramsEmploymentMyApplicationsRouteImport } from './routes/programs/employment/my-applications'
import { Route as ProgramsEmploymentApplyRouteImport } from './routes/programs/employment/apply'
import { Route as ProgramsEmploymentIdRouteImport } from './routes/programs/employment/$id'
import { Route as ProgramsEducationMyApplicationsRouteImport } from './routes/programs/education/my-applications'
import { Route as ProgramsEducationApplyRouteImport } from './routes/programs/education/apply'
import { Route as ProgramsEducationIdRouteImport } from './routes/programs/education/$id'
import { Route as AdminProgramsWelfareRouteImport } from './routes/admin/programs/welfare'
import { Route as AdminProgramsHealthRouteImport } from './routes/admin/programs/health'
import { Route as AdminProgramsEmploymentRouteImport } from './routes/admin/programs/employment'
import { Route as AdminProgramsEducationRouteImport } from './routes/admin/programs/education'
import { Route as AdminMembersIdRouteImport } from './routes/admin/members/$id'
import { Route as AdminProgramsWelfareIdRouteImport } from './routes/admin/programs/welfare/$id'
import { Route as AdminProgramsHealthIdRouteImport } from './routes/admin/programs/health/$id'
import { Route as AdminProgramsEmploymentIdRouteImport } from './routes/admin/programs/employment/$id'
import { Route as AdminProgramsEducationIdRouteImport } from './routes/admin/programs/education/$id'
import { Route as AdminMembersIdCardRouteImport } from './routes/admin/members/$id/card'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyMemberNoRoute = VerifyMemberNoRouteImport.update({
  id: '/verify/$memberNo',
  path: '/verify/$memberNo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsWelfareRoute = ProgramsWelfareRouteImport.update({
  id: '/programs/welfare',
  path: '/programs/welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsHealthRoute = ProgramsHealthRouteImport.update({
  id: '/programs/health',
  path: '/programs/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsEmploymentRoute = ProgramsEmploymentRouteImport.update({
  id: '/programs/employment',
  path: '/programs/employment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsEducationRoute = ProgramsEducationRouteImport.update({
  id: '/programs/education',
  path: '/programs/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const ProgramsWelfareMyApplicationsRoute =
  ProgramsWelfareMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => ProgramsWelfareRoute,
  } as any)
const ProgramsWelfareApplyRoute = ProgramsWelfareApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProgramsWelfareRoute,
} as any)
const ProgramsWelfareIdRoute = ProgramsWelfareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsWelfareRoute,
} as any)
const ProgramsHealthMyApplicationsRoute =
  ProgramsHealthMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => ProgramsHealthRoute,
  } as any)
const ProgramsHealthApplyRoute = ProgramsHealthApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProgramsHealthRoute,
} as any)
const ProgramsHealthIdRoute = ProgramsHealthIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsHealthRoute,
} as any)
const ProgramsEmploymentMyApplicationsRoute =
  ProgramsEmploymentMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => ProgramsEmploymentRoute,
  } as any)
const ProgramsEmploymentApplyRoute = ProgramsEmploymentApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProgramsEmploymentRoute,
} as any)
const ProgramsEmploymentIdRoute = ProgramsEmploymentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsEmploymentRoute,
} as any)
const ProgramsEducationMyApplicationsRoute =
  ProgramsEducationMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => ProgramsEducationRoute,
  } as any)
const ProgramsEducationApplyRoute = ProgramsEducationApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProgramsEducationRoute,
} as any)
const ProgramsEducationIdRoute = ProgramsEducationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsEducationRoute,
} as any)
const AdminProgramsWelfareRoute = AdminProgramsWelfareRouteImport.update({
  id: '/programs/welfare',
  path: '/programs/welfare',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsHealthRoute = AdminProgramsHealthRouteImport.update({
  id: '/programs/health',
  path: '/programs/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsEmploymentRoute = AdminProgramsEmploymentRouteImport.update({
  id: '/programs/employment',
  path: '/programs/employment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsEducationRoute = AdminProgramsEducationRouteImport.update({
  id: '/programs/education',
  path: '/programs/education',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsWelfareIdRoute = AdminProgramsWelfareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProgramsWelfareRoute,
} as any)
const AdminProgramsHealthIdRoute = AdminProgramsHealthIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProgramsHealthRoute,
} as any)
const AdminProgramsEmploymentIdRoute =
  AdminProgramsEmploymentIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminProgramsEmploymentRoute,
  } as any)
const AdminProgramsEducationIdRoute =
  AdminProgramsEducationIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminProgramsEducationRoute,
  } as any)
const AdminMembersIdCardRoute = AdminMembersIdCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AdminMembersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/programs/education': typeof ProgramsEducationRouteWithChildren
  '/programs/employment': typeof ProgramsEmploymentRouteWithChildren
  '/programs/health': typeof ProgramsHealthRouteWithChildren
  '/programs/welfare': typeof ProgramsWelfareRouteWithChildren
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/programs/education': typeof AdminProgramsEducationRouteWithChildren
  '/admin/programs/employment': typeof AdminProgramsEmploymentRouteWithChildren
  '/admin/programs/health': typeof AdminProgramsHealthRouteWithChildren
  '/admin/programs/welfare': typeof AdminProgramsWelfareRouteWithChildren
  '/programs/education/$id': typeof ProgramsEducationIdRoute
  '/programs/education/apply': typeof ProgramsEducationApplyRoute
  '/programs/education/my-applications': typeof ProgramsEducationMyApplicationsRoute
  '/programs/employment/$id': typeof ProgramsEmploymentIdRoute
  '/programs/employment/apply': typeof ProgramsEmploymentApplyRoute
  '/programs/employment/my-applications': typeof ProgramsEmploymentMyApplicationsRoute
  '/programs/health/$id': typeof ProgramsHealthIdRoute
  '/programs/health/apply': typeof ProgramsHealthApplyRoute
  '/programs/health/my-applications': typeof ProgramsHealthMyApplicationsRoute
  '/programs/welfare/$id': typeof ProgramsWelfareIdRoute
  '/programs/welfare/apply': typeof ProgramsWelfareApplyRoute
  '/programs/welfare/my-applications': typeof ProgramsWelfareMyApplicationsRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
  '/admin/programs/education/$id': typeof AdminProgramsEducationIdRoute
  '/admin/programs/employment/$id': typeof AdminProgramsEmploymentIdRoute
  '/admin/programs/health/$id': typeof AdminProgramsHealthIdRoute
  '/admin/programs/welfare/$id': typeof AdminProgramsWelfareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/programs/education': typeof ProgramsEducationRouteWithChildren
  '/programs/employment': typeof ProgramsEmploymentRouteWithChildren
  '/programs/health': typeof ProgramsHealthRouteWithChildren
  '/programs/welfare': typeof ProgramsWelfareRouteWithChildren
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/programs/education': typeof AdminProgramsEducationRouteWithChildren
  '/admin/programs/employment': typeof AdminProgramsEmploymentRouteWithChildren
  '/admin/programs/health': typeof AdminProgramsHealthRouteWithChildren
  '/admin/programs/welfare': typeof AdminProgramsWelfareRouteWithChildren
  '/programs/education/$id': typeof ProgramsEducationIdRoute
  '/programs/education/apply': typeof ProgramsEducationApplyRoute
  '/programs/education/my-applications': typeof ProgramsEducationMyApplicationsRoute
  '/programs/employment/$id': typeof ProgramsEmploymentIdRoute
  '/programs/employment/apply': typeof ProgramsEmploymentApplyRoute
  '/programs/employment/my-applications': typeof ProgramsEmploymentMyApplicationsRoute
  '/programs/health/$id': typeof ProgramsHealthIdRoute
  '/programs/health/apply': typeof ProgramsHealthApplyRoute
  '/programs/health/my-applications': typeof ProgramsHealthMyApplicationsRoute
  '/programs/welfare/$id': typeof ProgramsWelfareIdRoute
  '/programs/welfare/apply': typeof ProgramsWelfareApplyRoute
  '/programs/welfare/my-applications': typeof ProgramsWelfareMyApplicationsRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
  '/admin/programs/education/$id': typeof AdminProgramsEducationIdRoute
  '/admin/programs/employment/$id': typeof AdminProgramsEmploymentIdRoute
  '/admin/programs/health/$id': typeof AdminProgramsHealthIdRoute
  '/admin/programs/welfare/$id': typeof AdminProgramsWelfareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/programs/education': typeof ProgramsEducationRouteWithChildren
  '/programs/employment': typeof ProgramsEmploymentRouteWithChildren
  '/programs/health': typeof ProgramsHealthRouteWithChildren
  '/programs/welfare': typeof ProgramsWelfareRouteWithChildren
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/programs/education': typeof AdminProgramsEducationRouteWithChildren
  '/admin/programs/employment': typeof AdminProgramsEmploymentRouteWithChildren
  '/admin/programs/health': typeof AdminProgramsHealthRouteWithChildren
  '/admin/programs/welfare': typeof AdminProgramsWelfareRouteWithChildren
  '/programs/education/$id': typeof ProgramsEducationIdRoute
  '/programs/education/apply': typeof ProgramsEducationApplyRoute
  '/programs/education/my-applications': typeof ProgramsEducationMyApplicationsRoute
  '/programs/employment/$id': typeof ProgramsEmploymentIdRoute
  '/programs/employment/apply': typeof ProgramsEmploymentApplyRoute
  '/programs/employment/my-applications': typeof ProgramsEmploymentMyApplicationsRoute
  '/programs/health/$id': typeof ProgramsHealthIdRoute
  '/programs/health/apply': typeof ProgramsHealthApplyRoute
  '/programs/health/my-applications': typeof ProgramsHealthMyApplicationsRoute
  '/programs/welfare/$id': typeof ProgramsWelfareIdRoute
  '/programs/welfare/apply': typeof ProgramsWelfareApplyRoute
  '/programs/welfare/my-applications': typeof ProgramsWelfareMyApplicationsRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
  '/admin/programs/education/$id': typeof AdminProgramsEducationIdRoute
  '/admin/programs/employment/$id': typeof AdminProgramsEmploymentIdRoute
  '/admin/programs/health/$id': typeof AdminProgramsHealthIdRoute
  '/admin/programs/welfare/$id': typeof AdminProgramsWelfareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/donate'
    | '/donors'
    | '/login'
    | '/register'
    | '/signup'
    | '/admin/finance'
    | '/programs/education'
    | '/programs/employment'
    | '/programs/health'
    | '/programs/welfare'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/admin/programs/education'
    | '/admin/programs/employment'
    | '/admin/programs/health'
    | '/admin/programs/welfare'
    | '/programs/education/$id'
    | '/programs/education/apply'
    | '/programs/education/my-applications'
    | '/programs/employment/$id'
    | '/programs/employment/apply'
    | '/programs/employment/my-applications'
    | '/programs/health/$id'
    | '/programs/health/apply'
    | '/programs/health/my-applications'
    | '/programs/welfare/$id'
    | '/programs/welfare/apply'
    | '/programs/welfare/my-applications'
    | '/admin/members/$id/card'
    | '/admin/programs/education/$id'
    | '/admin/programs/employment/$id'
    | '/admin/programs/health/$id'
    | '/admin/programs/welfare/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/donate'
    | '/donors'
    | '/login'
    | '/register'
    | '/signup'
    | '/admin/finance'
    | '/programs/education'
    | '/programs/employment'
    | '/programs/health'
    | '/programs/welfare'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/admin/programs/education'
    | '/admin/programs/employment'
    | '/admin/programs/health'
    | '/admin/programs/welfare'
    | '/programs/education/$id'
    | '/programs/education/apply'
    | '/programs/education/my-applications'
    | '/programs/employment/$id'
    | '/programs/employment/apply'
    | '/programs/employment/my-applications'
    | '/programs/health/$id'
    | '/programs/health/apply'
    | '/programs/health/my-applications'
    | '/programs/welfare/$id'
    | '/programs/welfare/apply'
    | '/programs/welfare/my-applications'
    | '/admin/members/$id/card'
    | '/admin/programs/education/$id'
    | '/admin/programs/employment/$id'
    | '/admin/programs/health/$id'
    | '/admin/programs/welfare/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/donate'
    | '/donors'
    | '/login'
    | '/register'
    | '/signup'
    | '/admin/finance'
    | '/programs/education'
    | '/programs/employment'
    | '/programs/health'
    | '/programs/welfare'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/admin/programs/education'
    | '/admin/programs/employment'
    | '/admin/programs/health'
    | '/admin/programs/welfare'
    | '/programs/education/$id'
    | '/programs/education/apply'
    | '/programs/education/my-applications'
    | '/programs/employment/$id'
    | '/programs/employment/apply'
    | '/programs/employment/my-applications'
    | '/programs/health/$id'
    | '/programs/health/apply'
    | '/programs/health/my-applications'
    | '/programs/welfare/$id'
    | '/programs/welfare/apply'
    | '/programs/welfare/my-applications'
    | '/admin/members/$id/card'
    | '/admin/programs/education/$id'
    | '/admin/programs/employment/$id'
    | '/admin/programs/health/$id'
    | '/admin/programs/welfare/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CardRoute: typeof CardRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  DonorsRoute: typeof DonorsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  ProgramsEducationRoute: typeof ProgramsEducationRouteWithChildren
  ProgramsEmploymentRoute: typeof ProgramsEmploymentRouteWithChildren
  ProgramsHealthRoute: typeof ProgramsHealthRouteWithChildren
  ProgramsWelfareRoute: typeof ProgramsWelfareRouteWithChildren
  VerifyMemberNoRoute: typeof VerifyMemberNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$memberNo': {
      id: '/verify/$memberNo'
      path: '/verify/$memberNo'
      fullPath: '/verify/$memberNo'
      preLoaderRoute: typeof VerifyMemberNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/welfare': {
      id: '/programs/welfare'
      path: '/programs/welfare'
      fullPath: '/programs/welfare'
      preLoaderRoute: typeof ProgramsWelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/health': {
      id: '/programs/health'
      path: '/programs/health'
      fullPath: '/programs/health'
      preLoaderRoute: typeof ProgramsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/employment': {
      id: '/programs/employment'
      path: '/programs/employment'
      fullPath: '/programs/employment'
      preLoaderRoute: typeof ProgramsEmploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/education': {
      id: '/programs/education'
      path: '/programs/education'
      fullPath: '/programs/education'
      preLoaderRoute: typeof ProgramsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/programs/welfare/my-applications': {
      id: '/programs/welfare/my-applications'
      path: '/my-applications'
      fullPath: '/programs/welfare/my-applications'
      preLoaderRoute: typeof ProgramsWelfareMyApplicationsRouteImport
      parentRoute: typeof ProgramsWelfareRoute
    }
    '/programs/welfare/apply': {
      id: '/programs/welfare/apply'
      path: '/apply'
      fullPath: '/programs/welfare/apply'
      preLoaderRoute: typeof ProgramsWelfareApplyRouteImport
      parentRoute: typeof ProgramsWelfareRoute
    }
    '/programs/welfare/$id': {
      id: '/programs/welfare/$id'
      path: '/$id'
      fullPath: '/programs/welfare/$id'
      preLoaderRoute: typeof ProgramsWelfareIdRouteImport
      parentRoute: typeof ProgramsWelfareRoute
    }
    '/programs/health/my-applications': {
      id: '/programs/health/my-applications'
      path: '/my-applications'
      fullPath: '/programs/health/my-applications'
      preLoaderRoute: typeof ProgramsHealthMyApplicationsRouteImport
      parentRoute: typeof ProgramsHealthRoute
    }
    '/programs/health/apply': {
      id: '/programs/health/apply'
      path: '/apply'
      fullPath: '/programs/health/apply'
      preLoaderRoute: typeof ProgramsHealthApplyRouteImport
      parentRoute: typeof ProgramsHealthRoute
    }
    '/programs/health/$id': {
      id: '/programs/health/$id'
      path: '/$id'
      fullPath: '/programs/health/$id'
      preLoaderRoute: typeof ProgramsHealthIdRouteImport
      parentRoute: typeof ProgramsHealthRoute
    }
    '/programs/employment/my-applications': {
      id: '/programs/employment/my-applications'
      path: '/my-applications'
      fullPath: '/programs/employment/my-applications'
      preLoaderRoute: typeof ProgramsEmploymentMyApplicationsRouteImport
      parentRoute: typeof ProgramsEmploymentRoute
    }
    '/programs/employment/apply': {
      id: '/programs/employment/apply'
      path: '/apply'
      fullPath: '/programs/employment/apply'
      preLoaderRoute: typeof ProgramsEmploymentApplyRouteImport
      parentRoute: typeof ProgramsEmploymentRoute
    }
    '/programs/employment/$id': {
      id: '/programs/employment/$id'
      path: '/$id'
      fullPath: '/programs/employment/$id'
      preLoaderRoute: typeof ProgramsEmploymentIdRouteImport
      parentRoute: typeof ProgramsEmploymentRoute
    }
    '/programs/education/my-applications': {
      id: '/programs/education/my-applications'
      path: '/my-applications'
      fullPath: '/programs/education/my-applications'
      preLoaderRoute: typeof ProgramsEducationMyApplicationsRouteImport
      parentRoute: typeof ProgramsEducationRoute
    }
    '/programs/education/apply': {
      id: '/programs/education/apply'
      path: '/apply'
      fullPath: '/programs/education/apply'
      preLoaderRoute: typeof ProgramsEducationApplyRouteImport
      parentRoute: typeof ProgramsEducationRoute
    }
    '/programs/education/$id': {
      id: '/programs/education/$id'
      path: '/$id'
      fullPath: '/programs/education/$id'
      preLoaderRoute: typeof ProgramsEducationIdRouteImport
      parentRoute: typeof ProgramsEducationRoute
    }
    '/admin/programs/welfare': {
      id: '/admin/programs/welfare'
      path: '/programs/welfare'
      fullPath: '/admin/programs/welfare'
      preLoaderRoute: typeof AdminProgramsWelfareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs/health': {
      id: '/admin/programs/health'
      path: '/programs/health'
      fullPath: '/admin/programs/health'
      preLoaderRoute: typeof AdminProgramsHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs/employment': {
      id: '/admin/programs/employment'
      path: '/programs/employment'
      fullPath: '/admin/programs/employment'
      preLoaderRoute: typeof AdminProgramsEmploymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs/education': {
      id: '/admin/programs/education'
      path: '/programs/education'
      fullPath: '/admin/programs/education'
      preLoaderRoute: typeof AdminProgramsEducationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs/welfare/$id': {
      id: '/admin/programs/welfare/$id'
      path: '/$id'
      fullPath: '/admin/programs/welfare/$id'
      preLoaderRoute: typeof AdminProgramsWelfareIdRouteImport
      parentRoute: typeof AdminProgramsWelfareRoute
    }
    '/admin/programs/health/$id': {
      id: '/admin/programs/health/$id'
      path: '/$id'
      fullPath: '/admin/programs/health/$id'
      preLoaderRoute: typeof AdminProgramsHealthIdRouteImport
      parentRoute: typeof AdminProgramsHealthRoute
    }
    '/admin/programs/employment/$id': {
      id: '/admin/programs/employment/$id'
      path: '/$id'
      fullPath: '/admin/programs/employment/$id'
      preLoaderRoute: typeof AdminProgramsEmploymentIdRouteImport
      parentRoute: typeof AdminProgramsEmploymentRoute
    }
    '/admin/programs/education/$id': {
      id: '/admin/programs/education/$id'
      path: '/$id'
      fullPath: '/admin/programs/education/$id'
      preLoaderRoute: typeof AdminProgramsEducationIdRouteImport
      parentRoute: typeof AdminProgramsEducationRoute
    }
    '/admin/members/$id/card': {
      id: '/admin/members/$id/card'
      path: '/card'
      fullPath: '/admin/members/$id/card'
      preLoaderRoute: typeof AdminMembersIdCardRouteImport
      parentRoute: typeof AdminMembersIdRoute
    }
  }
}

interface AdminMembersIdRouteChildren {
  AdminMembersIdCardRoute: typeof AdminMembersIdCardRoute
}

const AdminMembersIdRouteChildren: AdminMembersIdRouteChildren = {
  AdminMembersIdCardRoute: AdminMembersIdCardRoute,
}

const AdminMembersIdRouteWithChildren = AdminMembersIdRoute._addFileChildren(
  AdminMembersIdRouteChildren,
)

interface AdminProgramsEducationRouteChildren {
  AdminProgramsEducationIdRoute: typeof AdminProgramsEducationIdRoute
}

const AdminProgramsEducationRouteChildren: AdminProgramsEducationRouteChildren =
  {
    AdminProgramsEducationIdRoute: AdminProgramsEducationIdRoute,
  }

const AdminProgramsEducationRouteWithChildren =
  AdminProgramsEducationRoute._addFileChildren(
    AdminProgramsEducationRouteChildren,
  )

interface AdminProgramsEmploymentRouteChildren {
  AdminProgramsEmploymentIdRoute: typeof AdminProgramsEmploymentIdRoute
}

const AdminProgramsEmploymentRouteChildren: AdminProgramsEmploymentRouteChildren =
  {
    AdminProgramsEmploymentIdRoute: AdminProgramsEmploymentIdRoute,
  }

const AdminProgramsEmploymentRouteWithChildren =
  AdminProgramsEmploymentRoute._addFileChildren(
    AdminProgramsEmploymentRouteChildren,
  )

interface AdminProgramsHealthRouteChildren {
  AdminProgramsHealthIdRoute: typeof AdminProgramsHealthIdRoute
}

const AdminProgramsHealthRouteChildren: AdminProgramsHealthRouteChildren = {
  AdminProgramsHealthIdRoute: AdminProgramsHealthIdRoute,
}

const AdminProgramsHealthRouteWithChildren =
  AdminProgramsHealthRoute._addFileChildren(AdminProgramsHealthRouteChildren)

interface AdminProgramsWelfareRouteChildren {
  AdminProgramsWelfareIdRoute: typeof AdminProgramsWelfareIdRoute
}

const AdminProgramsWelfareRouteChildren: AdminProgramsWelfareRouteChildren = {
  AdminProgramsWelfareIdRoute: AdminProgramsWelfareIdRoute,
}

const AdminProgramsWelfareRouteWithChildren =
  AdminProgramsWelfareRoute._addFileChildren(AdminProgramsWelfareRouteChildren)

interface AdminRouteChildren {
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminMembersIdRoute: typeof AdminMembersIdRouteWithChildren
  AdminProgramsEducationRoute: typeof AdminProgramsEducationRouteWithChildren
  AdminProgramsEmploymentRoute: typeof AdminProgramsEmploymentRouteWithChildren
  AdminProgramsHealthRoute: typeof AdminProgramsHealthRouteWithChildren
  AdminProgramsWelfareRoute: typeof AdminProgramsWelfareRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinanceRoute: AdminFinanceRoute,
  AdminMembersIdRoute: AdminMembersIdRouteWithChildren,
  AdminProgramsEducationRoute: AdminProgramsEducationRouteWithChildren,
  AdminProgramsEmploymentRoute: AdminProgramsEmploymentRouteWithChildren,
  AdminProgramsHealthRoute: AdminProgramsHealthRouteWithChildren,
  AdminProgramsWelfareRoute: AdminProgramsWelfareRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProgramsEducationRouteChildren {
  ProgramsEducationIdRoute: typeof ProgramsEducationIdRoute
  ProgramsEducationApplyRoute: typeof ProgramsEducationApplyRoute
  ProgramsEducationMyApplicationsRoute: typeof ProgramsEducationMyApplicationsRoute
}

const ProgramsEducationRouteChildren: ProgramsEducationRouteChildren = {
  ProgramsEducationIdRoute: ProgramsEducationIdRoute,
  ProgramsEducationApplyRoute: ProgramsEducationApplyRoute,
  ProgramsEducationMyApplicationsRoute: ProgramsEducationMyApplicationsRoute,
}

const ProgramsEducationRouteWithChildren =
  ProgramsEducationRoute._addFileChildren(ProgramsEducationRouteChildren)

interface ProgramsEmploymentRouteChildren {
  ProgramsEmploymentIdRoute: typeof ProgramsEmploymentIdRoute
  ProgramsEmploymentApplyRoute: typeof ProgramsEmploymentApplyRoute
  ProgramsEmploymentMyApplicationsRoute: typeof ProgramsEmploymentMyApplicationsRoute
}

const ProgramsEmploymentRouteChildren: ProgramsEmploymentRouteChildren = {
  ProgramsEmploymentIdRoute: ProgramsEmploymentIdRoute,
  ProgramsEmploymentApplyRoute: ProgramsEmploymentApplyRoute,
  ProgramsEmploymentMyApplicationsRoute: ProgramsEmploymentMyApplicationsRoute,
}

const ProgramsEmploymentRouteWithChildren =
  ProgramsEmploymentRoute._addFileChildren(ProgramsEmploymentRouteChildren)

interface ProgramsHealthRouteChildren {
  ProgramsHealthIdRoute: typeof ProgramsHealthIdRoute
  ProgramsHealthApplyRoute: typeof ProgramsHealthApplyRoute
  ProgramsHealthMyApplicationsRoute: typeof ProgramsHealthMyApplicationsRoute
}

const ProgramsHealthRouteChildren: ProgramsHealthRouteChildren = {
  ProgramsHealthIdRoute: ProgramsHealthIdRoute,
  ProgramsHealthApplyRoute: ProgramsHealthApplyRoute,
  ProgramsHealthMyApplicationsRoute: ProgramsHealthMyApplicationsRoute,
}

const ProgramsHealthRouteWithChildren = ProgramsHealthRoute._addFileChildren(
  ProgramsHealthRouteChildren,
)

interface ProgramsWelfareRouteChildren {
  ProgramsWelfareIdRoute: typeof ProgramsWelfareIdRoute
  ProgramsWelfareApplyRoute: typeof ProgramsWelfareApplyRoute
  ProgramsWelfareMyApplicationsRoute: typeof ProgramsWelfareMyApplicationsRoute
}

const ProgramsWelfareRouteChildren: ProgramsWelfareRouteChildren = {
  ProgramsWelfareIdRoute: ProgramsWelfareIdRoute,
  ProgramsWelfareApplyRoute: ProgramsWelfareApplyRoute,
  ProgramsWelfareMyApplicationsRoute: ProgramsWelfareMyApplicationsRoute,
}

const ProgramsWelfareRouteWithChildren = ProgramsWelfareRoute._addFileChildren(
  ProgramsWelfareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CardRoute: CardRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  DonorsRoute: DonorsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  ProgramsEducationRoute: ProgramsEducationRouteWithChildren,
  ProgramsEmploymentRoute: ProgramsEmploymentRouteWithChildren,
  ProgramsHealthRoute: ProgramsHealthRouteWithChildren,
  ProgramsWelfareRoute: ProgramsWelfareRouteWithChildren,
  VerifyMemberNoRoute: VerifyMemberNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
